egg.shell.Bat=FFFFFF
egg.shell.Blaze=FFFFFF
egg.shell.CaveSpider=FFFFFF
egg.shell.Chicken=FFFFFF
egg.shell.Cow=FFFFFF
egg.shell.Creeper=FFFFFF
egg.shell.Donkey=FFFFFF
egg.shell.ElderGuardian=FFFFFF
egg.shell.Enderman=FFFFFF
egg.shell.Endermite=FFFFFF
egg.shell.EntityHorse=FFFFFF
egg.shell.EvocationIllager=FFFFFF
egg.shell.Ghast=FFFFFF
egg.shell.Guardian=FFFFFF
egg.shell.Husk=FFFFFF
egg.shell.LavaSlime=FFFFFF
egg.shell.Llama=FFFFFF
egg.shell.Mule=FFFFFF
egg.shell.MushroomCow=FFFFFF
egg.shell.Ozelot=FFFFFF
egg.shell.Parrot=FFFFFF
egg.shell.Pig=FFFFFF
egg.shell.PigZombie=FFFFFF
egg.shell.PolarBear=FFFFFF
egg.shell.Rabbit=FFFFFF
egg.shell.Sheep=FFFFFF
egg.shell.Shulker=FFFFFF
egg.shell.Silverfish=FFFFFF
egg.shell.Skeleton=FFFFFF
egg.shell.SkeletonHorse=FFFFFF
egg.shell.Slime=FFFFFF
egg.shell.Spider=FFFFFF
egg.shell.Squid=FFFFFF
egg.shell.Stray=FFFFFF
egg.shell.Vex=FFFFFF
egg.shell.Villager=FFFFFF
egg.shell.VindicationIllager=FFFFFF
egg.shell.Witch=FFFFFF
egg.shell.WitherSkeleton=FFFFFF
egg.shell.Wolf=FFFFFF
egg.shell.Zombie=FFFFFF
egg.shell.ZombieHorse=FFFFFF
egg.shell.ZombieVillager=FFFFFF
egg.shell.horse=FFFFFF
xporb.time=350
text.xpbar=ff7001
sheep.orange=ff7001
text.code.6=ff7001
